apiVersion: apps/v1
kind: Deployment
metadata:
  name: orderservice
spec:
  replicas: 2
  selector:
    matchLabels:
      app: orderservice
  template:
    metadata:
      labels:
        app: orderservice
    spec:
      containers:
      - name: orderservice
        image: orderservice:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 8080
        env:
        - name: NATS_URL
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: NATS_URL
        - name: ORDER_SERVICE_PORT
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: ORDER_SERVICE_PORT
        - name: ACK_HANDLER_GOROUTINES
          value: "2000"
        - name: PUBLISH_TASK_QUEUE_SIZE
          value: "51200"
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: orderservice
spec:
  type: NodePort
  ports:
  - port: 8080
    targetPort: 8080
    name: http-metrics
    nodePort: 30080
  selector:
    app: orderservice 